"""Package the series for Instagram: one folder of post-ready images and captions.

  outputs/pylon-series/instagram/NNN.png   copy of the full render (2048 square —
                                           Instagram downscales to 1080 itself, so
                                           no resizing here; square posts natively)
  outputs/pylon-series/instagram/NNN.txt   caption + alt text, built from the
                                           piece's brief (spec meta.direction)
  outputs/pylon-series/instagram/queue.md  posting checklist in numeric order —
                                           piece numbers walk the design space in
                                           a decorrelated order by construction,
                                           so numeric order already varies the feed

Pieces without a full render are skipped with a warning — render them first:
  python scripts/render_pylons.py --pieces N --full

Usage:
  python scripts/export_instagram.py
"""

import glob
import json
import os
import shutil
import sys

# Warnings carry em-dashes; a cp949 console must not kill the export.
sys.stdout.reconfigure(encoding="utf-8", errors="replace")

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RULESET = "pylon-series"

TAGS = ("#pylonseries #generativeart #proceduralart #creativecoding "
        "#minimalart #powerlines #fog #blender3d")

ABOUT = ("From a series built from nothing but rules: a versioned prompt, a "
         "language model sampling inside it, deterministic validators, "
         "Blender/Cycles. The spec is the piece; the image reproduces from it "
         "exactly.\n\nRules and specs: github.com/tttptiii/objects")


def caption(n, spec):
    kind = (spec.get("terrain") or {}).get("kind") or "bare sky"
    brief = (spec.get("meta") or {}).get("direction", "").strip()
    alt = (f"{brief} " if brief else "") + (
        "A rules-generated graphic render of lattice transmission towers in fog.")
    parts = [f"{RULESET} {n:03d} — {kind}"]
    if brief:
        parts.append(brief)
    parts += [ABOUT, TAGS, f"ALT: {alt}"]
    return "\n\n".join(parts) + "\n"


def main():
    out_dir = os.path.join(ROOT, "outputs", RULESET, "instagram")
    os.makedirs(out_dir, exist_ok=True)
    queue = ["# Posting queue", "",
             "Generated by `scripts/export_instagram.py` — check off as posted.", ""]
    exported = skipped = 0
    for path in sorted(glob.glob(os.path.join(ROOT, "scenes", RULESET, "[0-9]*.json"))):
        n = int(os.path.basename(path)[:3])
        with open(path, encoding="utf-8") as f:
            spec = json.load(f)
        src = os.path.join(ROOT, "outputs", RULESET, "full", f"{n:03d}.png")
        if not os.path.exists(src):
            print(f"[export] warning: no full render for {n:03d} — skipped "
                  f"(python scripts/render_pylons.py --pieces {n} --full)")
            skipped += 1
            continue
        shutil.copyfile(src, os.path.join(out_dir, f"{n:03d}.png"))
        with open(os.path.join(out_dir, f"{n:03d}.txt"), "w", encoding="utf-8") as f:
            f.write(caption(n, spec))
        kind = (spec.get("terrain") or {}).get("kind") or "bare sky"
        queue.append(f"- [ ] {n:03d} — {kind}")
        exported += 1
    with open(os.path.join(out_dir, "queue.md"), "w", encoding="utf-8") as f:
        f.write("\n".join(queue) + "\n")
    print(f"[export] {exported} pieces -> {out_dir}" +
          (f" ({skipped} skipped, no full render)" if skipped else ""))


if __name__ == "__main__":
    main()
