"""Generate the series manifest and a contact sheet from the specs on disk.

Two outputs, one source of truth (the spec files):

  docs/pieces.md                        tracked — what every piece number is, at a
                                        glance, for someone reading the repo
  outputs/pylon-series/contact.html     untracked — a local grid of the draft
                                        renders with their briefs and palettes,
                                        for reviewing a batch in one page

Usage:
  python scripts/report_pylons.py
"""

import glob
import html
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from colorutil import oklch_to_hex  # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RULESET = "pylon-series"


def load_pieces():
    pieces = []
    for path in sorted(glob.glob(os.path.join(ROOT, "scenes", RULESET, "[0-9]*.json"))):
        with open(path, encoding="utf-8") as f:
            spec = json.load(f)
        pieces.append((int(os.path.basename(path)[:3]), spec))
    return pieces


def describe(spec):
    kind = (spec.get("terrain") or {}).get("kind") or "bare sky"
    span = spec.get("span")
    rhythm = "uneven" if isinstance(span, list) else "even"
    scale = spec.get("tower_scale", 1.0)
    ins = spec.get("insulators", "I")
    anchor = (spec.get("palette") or {}).get("horizon")
    return kind, rhythm, scale, ins, anchor


def write_manifest(pieces):
    superseded = sorted(glob.glob(os.path.join(ROOT, "scenes", "superseded", "*.json")))
    lines = [
        "# Pieces",
        "",
        "Generated by `scripts/report_pylons.py` — do not edit by hand.",
        "",
        "Piece numbers are permanent: a number keeps its creative brief forever "
        "(`rulesets/pylon-series/directions.json`), so resampling a piece never changes "
        "what it is about. Gaps in the numbering are pieces whose direction era was "
        "retired; their specs live in `scenes/superseded/`.",
        "",
        "| piece | stage | line | anchor | model | rules | date |",
        "|---|---|---|---|---|---|---|",
    ]
    for n, spec in pieces:
        kind, rhythm, scale, ins, anchor = describe(spec)
        meta = spec.get("meta", {})
        line = f"scale {scale}, {ins}-strings, {rhythm} spans"
        anchor_s = ("`" + " ".join(f"{v:g}" for v in anchor) + "`") if anchor else "—"
        lines.append(
            f"| {n:03d} | {kind} | {line} | {anchor_s} | {meta.get('model', '?')} "
            f"| `{meta.get('rules_sha', '?')}` | {meta.get('date', '?')} |")
    lines += [
        "",
        f"Active pieces: {len(pieces)}. Superseded specs: {len(superseded)} "
        "(`scenes/superseded/`). Rejected candidates: "
        "`scenes/pylon-series/rejected/`. Judgments: "
        "`rulesets/pylon-series/judgments/`.",
        "",
    ]
    path = os.path.join(ROOT, "docs", "pieces.md")
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    return path


def write_contact(pieces):
    cards = []
    for n, spec in pieces:
        kind, rhythm, scale, ins, anchor = describe(spec)
        meta = spec.get("meta", {})
        swatch = ""
        if anchor:
            swatch = (f'<span class="sw" style="background:{oklch_to_hex(*anchor)}">'
                      "</span>")
        direction = html.escape(meta.get("direction", ""))
        cards.append(f"""
<div class="card">
  <img src="draft/{n:03d}.png" loading="lazy">
  <div class="cap">
    <b>{n:03d}</b> · {kind} {swatch}<br>
    scale {scale} · {ins}-strings · {rhythm} spans · <code>{meta.get('rules_sha', '?')}</code>
    <p>{direction}</p>
  </div>
</div>""")
    page = f"""<!doctype html>
<meta charset="utf-8">
<title>pylon-series — contact sheet</title>
<style>
  body {{ background: #16181c; color: #cfd3da; font: 13px/1.5 system-ui, sans-serif;
         margin: 2rem; }}
  .grid {{ display: grid; grid-template-columns: repeat(auto-fill, minmax(320px, 1fr));
           gap: 1.2rem; }}
  .card img {{ width: 100%; display: block; border-radius: 4px; }}
  .cap {{ padding: .5rem .2rem; }}
  .cap p {{ margin: .35rem 0 0; color: #8b93a0; }}
  .sw {{ display: inline-block; width: .8em; height: .8em; border-radius: 50%;
         vertical-align: -1px; border: 1px solid #444; }}
  code {{ color: #7c8698; }}
</style>
<h1>pylon-series — {len(pieces)} pieces</h1>
<div class="grid">{"".join(cards)}
</div>
"""
    path = os.path.join(ROOT, "outputs", RULESET, "contact.html")
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write(page)
    return path


def main():
    pieces = load_pieces()
    print(f"[report] {write_manifest(pieces)}")
    print(f"[report] {write_contact(pieces)}")


if __name__ == "__main__":
    main()
