"""Generate the series manifest, thumbnails, and a contact sheet from the specs.

Three outputs, one source of truth (the spec files):

  docs/thumbs/NNN.png                   tracked — the draft renders (640px) copied
                                        in as the series' small visual record; the
                                        full-size renders stay untracked and
                                        reproducible
  docs/pieces.md                        tracked — gallery + manifest table: what
                                        every piece number is, at a glance
  outputs/pylon-series/contact.html     untracked — a local grid of the draft
                                        renders with their briefs and palettes,
                                        for reviewing a batch in one page

Usage:
  python scripts/report_pylons.py            # regenerate all three
  python scripts/report_pylons.py --check    # is docs/pieces.md still current?
"""

import argparse
import glob
import html
import json
import os
import shutil
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import ruleset  # noqa: E402
from colorutil import oklch_to_hex  # noqa: E402
from render_pylons import render_sha, stamped_sha  # noqa: E402
from survey_composition import feed_selection, measured_pieces  # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RULESET = "pylon-series"


def load_pieces():
    pieces = []
    for path in sorted(glob.glob(os.path.join(ROOT, "scenes", RULESET, "[0-9]*.json"))):
        with open(path, encoding="utf-8") as f:
            spec = json.load(f)
        pieces.append((int(os.path.basename(path)[:3]), spec))
    return pieces


def describe(spec):
    kind = (spec.get("terrain") or {}).get("kind") or "bare sky"
    span = spec.get("span")
    rhythm = "uneven" if isinstance(span, list) else "even"
    scale = spec.get("tower_scale", 1.0)
    ins = spec.get("insulators", "I")
    anchor = (spec.get("palette") or {}).get("horizon")
    return kind, rhythm, scale, ins, anchor


def tracked_thumbs(pieces):
    """Piece numbers that have a thumbnail on disk. This — not the untracked draft
    folder — is what the gallery is built from, so a fresh clone with no renders
    reproduces the same docs/pieces.md instead of erasing it."""
    tdir = os.path.join(ROOT, "docs", "thumbs")
    return {n for n, _ in pieces
            if os.path.exists(os.path.join(tdir, f"{n:03d}.png"))}


# Blender stamps the wall-clock date and its own timing into every PNG it writes, so
# re-rendering an unchanged scene produces a byte-different file with bit-identical
# pixels. Tracked thumbnails would then churn on every render, and "this image changed"
# would stop meaning anything in a diff. Chunks are self-contained and carry their own
# CRC, so dropping these by name is safe and needs no re-encoding.
VOLATILE_PNG_CHUNKS = {b"tEXt", b"iTXt", b"zTXt", b"tIME", b"eXIf"}


def copy_png_without_timestamps(src, dst):
    with open(src, "rb") as f:
        data = f.read()
    out, i = [data[:8]], 8
    while i < len(data):
        length = int.from_bytes(data[i:i + 4], "big")
        end = i + 12 + length
        if data[i + 4:i + 8] not in VOLATILE_PNG_CHUNKS:
            out.append(data[i:end])
        i = end
    with open(dst, "wb") as f:
        f.write(b"".join(out))


def write_thumbs(pieces):
    """Refresh the tracked thumbnails from the draft renders, where those exist.
    Full renders stay untracked (reproducible from the specs)."""
    tdir = os.path.join(ROOT, "docs", "thumbs")
    os.makedirs(tdir, exist_ok=True)
    for n, _spec in pieces:
        src = os.path.join(ROOT, "outputs", RULESET, "draft", f"{n:03d}.png")
        if os.path.exists(src):
            copy_png_without_timestamps(src, os.path.join(tdir, f"{n:03d}.png"))
        elif not os.path.exists(os.path.join(tdir, f"{n:03d}.png")):
            print(f"[report] warning: no draft render and no thumbnail for {n:03d}")
    # drop thumbnails whose piece no longer exists
    active = {n for n, _ in pieces}
    for path in glob.glob(os.path.join(tdir, "[0-9]*.png")):
        if int(os.path.basename(path)[:3]) not in active:
            os.remove(path)
    return tracked_thumbs(pieces)


def manifest_text(pieces, thumbs):
    superseded = sorted(glob.glob(os.path.join(ROOT, "scenes", "superseded", "*.json")))
    lines = [
        "# Pieces",
        "",
        "Generated by `scripts/report_pylons.py` — do not edit by hand.",
        "",
        "Piece numbers are permanent: a number keeps its creative brief forever "
        "(`rulesets/pylon-series/directions.json`), so resampling a piece never changes "
        "what it is about. Gaps in the numbering are pieces whose direction era was "
        "retired; their specs live in `scenes/superseded/`.",
        "",
        "## Gallery",
        "",
    ]
    row = [(n, s) for n, s in pieces if n in thumbs]
    for i in range(0, len(row), 4):
        chunk = row[i:i + 4]
        lines.append("| " + " | ".join(f"{n:03d}" for n, _ in chunk) + " |")
        lines.append("|" + "---|" * len(chunk))
        lines.append("| " + " | ".join(f"![](thumbs/{n:03d}.png)" for n, _ in chunk)
                     + " |")
        lines.append("")
    lines += [
        "## Manifest",
        "",
        "| piece | stage | line | anchor | model | rules | date |",
        "|---|---|---|---|---|---|---|",
    ]
    for n, spec in pieces:
        kind, rhythm, scale, ins, anchor = describe(spec)
        meta = spec.get("meta", {})
        line = f"scale {scale}, {ins}-strings, {rhythm} spans"
        anchor_s = ("`" + " ".join(f"{v:g}" for v in anchor) + "`") if anchor else "—"
        lines.append(
            f"| {n:03d} | {kind} | {line} | {anchor_s} | {meta.get('model', '?')} "
            f"| `{meta.get('rules_sha', '?')}` | {meta.get('date', '?')} |")
    lines += [
        "",
        f"Active pieces: {len(pieces)}. Superseded specs: {len(superseded)} "
        "(`scenes/superseded/`). Rejected candidates: "
        "`scenes/pylon-series/rejected/`. Judgments: "
        "`rulesets/pylon-series/judgments/`.",
        "",
        # The live hash, not the stamp the drafts carry: this file must regenerate
        # identically on a machine that has no outputs/ at all, which is what lets CI
        # check it. The stamp answers a different question, in check_manifest.
        f"Renderer `{render_sha()}` — a content hash of `pylon3d.py` and "
        "`render_pylon3d.py`. A spec names the picture; a spec and this hash together "
        "name the file.",
        "",
    ]
    shown, skipped = feed_selection(measured_pieces(), ruleset.load(RULESET)["feed"])
    if skipped:
        lines += [
            f"The feed publishes {len(shown)} of these. The other {len(skipped)} stand "
            "in a place the feed already shows, so it passes over them — "
            + ", ".join(f"{n:03d} after {d:03d}" for n, d in sorted(skipped.items()))
            + ". They stay in the series: what the rules made is the record, and the "
            "account is a reading of it. Thresholds live in `checks.json` under "
            "`feed`.",
            "",
        ]
    return "\n".join(lines)


def write_manifest(pieces, thumbs):
    path = os.path.join(ROOT, "docs", "pieces.md")
    with open(path, "w", encoding="utf-8") as f:
        f.write(manifest_text(pieces, thumbs))
    return path


def write_contact(pieces):
    cards = []
    for n, spec in pieces:
        kind, rhythm, scale, ins, anchor = describe(spec)
        meta = spec.get("meta", {})
        swatch = ""
        if anchor:
            swatch = (f'<span class="sw" style="background:{oklch_to_hex(*anchor)}">'
                      "</span>")
        direction = html.escape(meta.get("direction", ""))
        cards.append(f"""
<div class="card">
  <img src="draft/{n:03d}.png" loading="lazy">
  <div class="cap">
    <b>{n:03d}</b> · {kind} {swatch}<br>
    scale {scale} · {ins}-strings · {rhythm} spans · <code>{meta.get('rules_sha', '?')}</code>
    <p>{direction}</p>
  </div>
</div>""")
    page = f"""<!doctype html>
<meta charset="utf-8">
<title>pylon-series — contact sheet</title>
<style>
  body {{ background: #16181c; color: #cfd3da; font: 13px/1.5 system-ui, sans-serif;
         margin: 2rem; }}
  .grid {{ display: grid; grid-template-columns: repeat(auto-fill, minmax(320px, 1fr));
           gap: 1.2rem; }}
  .card img {{ width: 100%; display: block; border-radius: 4px; }}
  .cap {{ padding: .5rem .2rem; }}
  .cap p {{ margin: .35rem 0 0; color: #8b93a0; }}
  .sw {{ display: inline-block; width: .8em; height: .8em; border-radius: 50%;
         vertical-align: -1px; border: 1px solid #444; }}
  code {{ color: #7c8698; }}
</style>
<h1>pylon-series — {len(pieces)} pieces</h1>
<div class="grid">{"".join(cards)}
</div>
"""
    path = os.path.join(ROOT, "outputs", RULESET, "contact.html")
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write(page)
    return path


def check_manifest(pieces):
    """Is the tracked manifest what the specs would generate right now? Sampling a
    piece and forgetting to regenerate leaves docs/pieces.md quietly wrong, and it is
    the page that says what every number is."""
    # Ask about the renderer first: a stale manifest is a regeneration away, but stale
    # images need Blender, and reporting the cheaper fault first sends the reader down
    # the wrong path. Comparing the live renderer against the stamp the drafts carry
    # also means regenerating alone cannot make this pass while the images stay old.
    draft_dir = os.path.join(ROOT, "outputs", RULESET, "draft")
    drafts_sha, live = stamped_sha(draft_dir), render_sha()
    if drafts_sha is not None and drafts_sha != live:
        sys.exit(f"[report] the renderer changed since these images were made "
                 f"({drafts_sha} -> {live}) — re-render before regenerating: "
                 f"python scripts/render_pylons.py --pieces 0-{max(n for n, _ in pieces)}")
    thumbs = tracked_thumbs(pieces)
    path = os.path.join(ROOT, "docs", "pieces.md")
    on_disk = ""
    if os.path.exists(path):
        with open(path, encoding="utf-8") as f:
            on_disk = f.read()
    if on_disk != manifest_text(pieces, thumbs):
        sys.exit("[report] docs/pieces.md is stale — regenerate it: "
                 "python scripts/report_pylons.py")
    print(f"[report] docs/pieces.md is current ({len(pieces)} pieces, "
          f"{len(thumbs)} thumbnails)")


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--check", action="store_true",
                    help="verify docs/pieces.md matches the specs; write nothing")
    args = ap.parse_args()
    pieces = load_pieces()
    if args.check:
        return check_manifest(pieces)
    thumbs = write_thumbs(pieces)
    print(f"[report] docs/thumbs: {len(thumbs)} thumbnails")
    print(f"[report] {write_manifest(pieces, thumbs)}")
    print(f"[report] {write_contact(pieces)}")


if __name__ == "__main__":
    main()
